### ISSUE TITLE
bootnavbar failing - $(...).bootnavbar is not a function

### ISSUE THREAD

**Issue by kitsguru** [kmlpandey77/bootnavbar#9]
For some reason I am getting an error that bootnavbar is not a function. This was working fine just yesterday. I am using the cdn for jquery and bootnavbar.

I have traced that the files are all loading but can't figure out why this error is now appearing.

It fails in Firefox and Chrome.

Any thoughts on how to fix or suggestions on how else to trouble shoot?

**Comment by kitsguru** [comment]
reverted to 1.0.2 and it is now working

**Comment by kitsguru** [comment]
MORE INFO:
It appears that v1.1.0 was moved to CDN without versioning two days ago. This version does not work with jquery and Readme instructions are incorrect. 

Workaround: Downloaded 1.0.2 and installed locally.

Hopefully the Readme will be updated soon.

**Comment by miwiwa** [comment]
Thank you for posting this.  You saved me a lot of time

**Comment by kitsguru** [comment]
I spent a bit more time and figured out the correct method to use v1.1.0

```
// new way
bootnavbar('primarynav');
bootnavbar('secondary-nav');
// old way
// $(function () {
//     $('#primarynav').bootnavbar();
//     $('#secondary-nav').bootnavbar();
// });
```

**Comment by kmlpandey77** [comment]
I will update docs soon

**Comment by kmlpandey77** [comment]
Docs updated
